version: '3.8'

services:
  mongo:
    image: mongo:6.0.2
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  api:
    depends_on:
      - mongo
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - DB_URI=mongodb://mongo:27017/27017
    stdin_open: true
    tty: true

volumes:
  db:
