export const USER_RESPONSE_MESSAGE = {
  emailExists: 'Email already exists',
  leadGenEmailExists: 'Lead gen email already exists',
  emailDoesNotExist: 'Email does not exist',
  industryLimit: 'Industries exceeds the limit of 3',
  createSuccess: 'Create user successfully',
  createError: 'Create user error',
  resetPasswordSuccess: 'Reset password user successfully',
  getInfoSuccess: 'Get information  successfully',
  confirmNotMatch: 'Confirm password does not match',
  notFound: 'User not found',
  getSuccess: 'Get user successfully',
  getError: 'Get user error',
  updateSuccess: 'Update user successfully',
  updateLinkedinSuccess: 'Update linkedin credentials successfully',
  updateProfileSuccess: 'Your changes have been saved',
  updateProfileError: `Your changes haven't been saved`,
  updatePasswordSuccess: 'Update password successfully',
  updatePasswordError: 'Update password error',
  updateError: 'Update user error',
  canNotCreate: 'Can not create user',
  payFailed: 'Pay failed',
  deleteSuccess: 'Delete user successfully',
  onlyDeleteUser: 'You cannot just delete user',
  onlyDeactivateUser:
    'Cannot delete the only Admin. Please assign another Admin before deleting this account.',
  forgotPasswordSuccess:
    "We've sent you a link to reset your password - please check your email!",
  resendSubscriptionSuccess: 'Resend subscription successfully',
  resendResetPwLinkSuccess: 'Resend reset password link successfully',
  canNotSubmitResponse: 'Can not submit response',
  companyNotYet: 'Please create company',
  emailPermission:
    'Please choose Share My Email at previous authentication step',
  resetSocialLoginSuccess: 'Reset Social Logins successful',
  userIsDeactivated: 'User is deactivated',
  reactivateUser: 'User is reactivated',
  restrictedUser: 'User is restricted',
  unrestrictedUser: 'User is unrestricted',
  getReferralCodeSuccess: 'Get referral code successful',
  Success: 'Success',
  addDeviceToken: 'Add device token successful',
  removeDeviceToken: 'Remove device token successful',
};
